# Generated by Django 3.1.3 on 2020-11-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
